### ISSUE TITLE
Bug in the checkUser middleware function

### ISSUE THREAD

**Issue by Piyush-onGIT** [Piyush-onGIT/PM#54]
# Description
The middleware function ```checkUser``` is passed to every route in ```userRoutes```. So usually all the endpoints must be checked for the JWT token in the cookie and validate the token, if the cookie is invalid or not present, it should return 401 status. But currently, it is bypassing the authentication.

# To reproduce the issue
Go to the ```pm-server``` folder, then, run the following command:
```bash
npm start
```
The server is running locally. After this, log in with a valid phone number and password. And then try some of the endpoints defined under ```userRoutes```. Now delete the cookie saved in the Postman and try the endpoints again.

For testing purposes:
Phone: 916202872652
Password: 1234

**Comment by gracious7** [comment]
@Piyush-onGIT I am unble to get cookies.

**Comment by Piyush-onGIT** [comment]
> @Piyush-onGIT I am unble to get cookies.

Hi @gracious7, actually the saving of cookies in the browser is done using a method ```res.cookies()``` which is defined under ```userController.js``` and ```authController.js```. And you can see a commented function for the same, the commented part is used for local testing and the current method to save cookies is used in production. So to save cookies in your browser, comment the one that is used for production and uncomment the one to test it locally.
